url: https://farseersserver.github.io
baseurl: 

# Site settings
title: Farseers Server
email: farseersserver@gmail.com
description: "farseers server"

# Team names, titles and social links
people:
- name:
    en: Erik Park
    ko: 박준석
  pic: 1
  position:
    en: Lead Designer
    ko: Lead Designer

- name:
    en: Sewoong Jeon
    ko: 전세웅
  pic: 2
  position:
    en: Lead Programmer
    ko: Lead Programmer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: commenting
    url: https://open.kakao.com/o/gQFDzzYe
  - title: discord
    url: https://discord.gg/VBfFtJp5Tc

# Build settings
markdown: kramdown
permalink: pretty
